### ISSUE TITLE
I have migrated your patches from branch 5.3 to 5.6/5.7 (based on upstream tag 5.6.4/5.7.1)

### ISSUE THREAD

**Issue by axelsommerfeldt** [herlesupreeth/kamailio#1]
Hi!

I have migrated your patches from your branch 5.3 to version 5.6.4 of kamailio, and the end result seems to work. (Tested on Debian 11)

https://github.com/axelsommerfeldt/kamailio_herlesupreeth/tree/5.6

Maybe this is of interest for you. Unfortunately I cannot create a Pull Request since you don't have a branch based on version 5.6(.4) yet.

Regards,
Axel

P.S.: Do you have any plans to push your changes (or part of them) to upstream?

**Comment by herlesupreeth** [comment]
Wow!! That cool and thanks a lot for your effort. I will create a new branch 5.6 and reach out to you for a PR.

> P.S.: Do you have any plans to pull your changes (or part of them) to upstream?

Currently no plans since I feel the fixes I gave are not the best in coding standard. But feel free to use my commit and issue PR to upstream repo so that others can also benefit.

**Comment by axelsommerfeldt** [comment]
I have done the same for Kamailio 5.7.1: https://github.com/axelsommerfeldt/kamailio_herlesupreeth/tree/5.7

But: While I was quite sure I know what I'm doing while patching version 5.6, I'm not sure anymore while patching 5.7 since the upstream code has further moved away from the base of your patches, especially the ipsec stuff.

I'll try to extract patches and convert them into upstream PRs next week, starting with obvious/easy fixes and non-ipsec stuff. The ipsec patches are a different matter, I don't think I can do something useful here (apart from obvious fixes) without help.

**Comment by herlesupreeth** [comment]
Hey @axelsommerfeldt sorry, I didnt get back to you on this. I will fork out branch 5.6 and 5.7 now so that you can issue PR against that. Thanks again for your work.

**Comment by herlesupreeth** [comment]
@axelsommerfeldt I have created branches 5.6 and 5.7, please issue a PR against those branches. Thank you

**Comment by axelsommerfeldt** [comment]
@herlesupreeth A big sorry for the delay, but I finally found some time to compare all patches to 5.7 (again) to see what patches have potential for being wrongly migrated. (For a list see PR #6 ) Furthermore I have rebased them to the current upstream version 5.7.2.

**Comment by herlesupreeth** [comment]
Hey, thanks a lot for your efforts. Sorry for the delay in responding, I was on a vacation. Will review your MRs in the coming week.

**Comment by herlesupreeth** [comment]
Hey, for this I would need more time so plan to keep this task around Christmas time. Sorry for the delay
