### ISSUE TITLE
ims_auth issue with Google pixel 6a

### ISSUE THREAD

**Issue by svinson1121** [herlesupreeth/kamailio#8]
Hey Supreeth,

this was tested with two UE's one iPhone and one Pixel 6a, the same SIM was used in each UE. 
iPhone has no issue, but the Pixel gives this Auth error on the SCSCF with a null nc value 

```
**INFO: ims_auth [authorize.c:827]: authenticate(): uri=sip:ims.mnc004.mcc310.3gppnetwork.org nonce=AaffvN2lyIEwVeepJh8VYF6JEwD2zYAAtiFkP1ahcE4= response=c51cd272cc212bdb48115cf58e490a44 qop=auth nc= cnonce=dd2448c1781ccb083197c4d0bc805143 hbody=

ERROR: ims_auth [authorize.c:852]: authenticate(): qop specified with no nonce count... failing**
```

Take a look at the attached PCAP's and you can see the  nc=  value is present in both, but it looks little different in the pixel PCAP.
I'm not sure if that's the root of the issue but it appears something is causing the nc value not to be parsed by the ims_auth module.
what are your thoughts on this?

Thank you for your help,

 
[PCAPS.zip](https://github.com/herlesupreeth/kamailio/files/13630978/PCAPS.zip)

**Comment by herlesupreeth** [comment]
Technically its the Pixel 6a fault for sending Authorization header in SIP REGISTER in a bad way. Notice that its should have been as follows but there is extra line break after `auth`. You can try putting the phone in safe-mode and restarting from safe mode to see if that fixes the issue. If not, then I would suggest to add the below parameter in kamailio_scscf.cfg file `modparam("ims_auth", "registration_qop", "auth")`

```
QOP:auth,auth-int
Nonce Count:00000001
```

![image](https://github.com/herlesupreeth/kamailio/assets/4115839/a3cb4728-69bc-4483-b9c9-e99a87781a6b)

**Comment by svinson1121** [comment]
Thank you Supreeth, you're the Man!  changing the registration_qop parameter resolved the issue. 
Thank you verry much for your input and all the work you have put into Kamailio IMS!
